"""Минимальный Python-клиент. Запуск:

    pip install grpcio grpcio-tools
    python -m grpc_tools.protoc -I../../proto --python_out=. --grpc_python_out=. unison.proto
    python hello.py 1
"""
import os
import sys

import grpc

import unison_pb2  # type: ignore[import-not-found]  # generated by protoc, see README
import unison_pb2_grpc  # type: ignore[import-not-found]

addr = os.environ.get("UNISON_GRPC_ADDR", "localhost:9290")
device_id = sys.argv[1] if len(sys.argv) > 1 else "1"
world = os.environ.get("UNISON_WORLD", "default")

channel = grpc.insecure_channel(addr)

target = unison_pb2.DeviceTarget(device_id=device_id, world_id=world)

devices = unison_pb2_grpc.DevicesStub(channel)
print("devices:", [d.device_id for d in devices.List(unison_pb2.ListDevicesReq(world_id=world)).devices])

turtle = unison_pb2_grpc.TurtleStub(channel)
print("forward →", turtle.Forward(unison_pb2.TurtleNoArgs(target=target)))

os_svc = unison_pb2_grpc.OsStub(channel)
print("computer id →", os_svc.GetComputerID(unison_pb2.TurtleNoArgs(target=target)))
